describe('mobile keyboard', () => {
  it('types on mobile keyboard', () => {
    cy.visit('http://localhost:4200/chat')
    cy.url().should('include', '/chat')
    cy.contains('___')
    cy.get('[data-skbtn="c"]').click()
    cy.get('[data-skbtn="a"]').click()
    cy.get('[data-skbtn="d"]').click()
    cy.get('[data-skbtn="{space}"]').click()
    cy.get('[data-skbtn="{fada}"]').click()
    cy.get('[data-skbtn="é"]').click()
    cy.get('[data-skbtn="{space}"]').click()
    cy.get('[data-skbtn="m"]').click()
    cy.get('[data-skbtn="a"]').click()
    cy.get('[data-skbtn="r"]').click()
    cy.get('[data-skbtn="{space}"]').click()
    cy.get('[data-skbtn="a"]').click()
    cy.get('[data-skbtn="t"]').click()
    cy.get('[data-skbtn="{fada}"]').click()
    cy.get('[data-skbtn="á"]').click()
    cy.get('[data-skbtn="{space}"]').click()
    cy.get('[data-skbtn="s"]').click()
    cy.get('[data-skbtn="i"]').click()
    cy.get('[data-skbtn="b"]').click()
    cy.get('[data-skbtn="h"]').click()
    cy.get('[data-skbtn="{bksp}"]').click()
    cy.get('[data-skbtn="{bksp}"]').click()
    cy.get('[data-skbtn="{bksp}"]').click()
    cy.get('[data-skbtn="{bksp}"]').click()
    cy.get('[data-skbtn="t"]').click()
    cy.get('[data-skbtn="{fada}"]').click()
    cy.get('[data-skbtn="ú"]').click()
    cy.get('[data-skbtn="{fada}"]').click()
    cy.get('[data-skbtn="{enter}"]').click()
    cy.contains('cad é mar atá tú')
    cy.contains('mícheart')
  })
})
